<?php
use AtDataGrid\DataGrid\Column\Column;
use Nette\Diagnostics\Debugger;
use Zend\Form\Form;

$form = $this->grid->getFiltersForm();
$form->prepare();
$form->setAttribute('action', $this->url(null, array(
	'action' => 'list'
)));
$form->setAttribute('method', 'get');
$form->setAttribute('id', 'datagrid-filters-form');

$this instanceof Zend\View\Renderer\PhpRenderer;
$filtersClean = array();
echo $this->form()->openTag($form);

$treeColumnsPrint = function  (Column $column, $form) use( &$treeColumnsPrint, 
$filtersClean)
{
	$html = '';
	if ($column->isVisible()) {
		
		$columns = (array) $column->getcolumns();
		$visibleSubcolumns = array();
		foreach ($columns as $_column) {
			if ($_column->isVisible()) {
				$visibleSubcolumns[] = $_column;
			}
		}
		
		if ($columns && count($visibleSubcolumns) > 0) {
			foreach ($visibleSubcolumns as $_column) {
				
				$form instanceof Form;
				$fieldset = $form->getFieldsets();
				$html .= $treeColumnsPrint($_column, 
						$fieldset[$column->getName()]);
			}
		} else {
			$html .= '<td>';
			if ($column->hasFilters()) {
				foreach ($column->getFilters() as $filter) {
					$filtersClean[$filter->getName()] = null;
					$html .= '<div class="row">
							  <div class="col-lg-12">
							    <div class="input-group">
							      <div class="input-group-btn" data-toggle="tooltip" data-container="body"  title="Elije que acciones ejecutar al filtrar">
							        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"><i class="glyphicon glyphicon-cog"></i> <span class="caret"></span></button>
							        <ul class="dropdown-menu">
							          <li><a data-value="Equal" href="#">Igual que</a></li>
							          <li><a data-value="GreaterThan" href="#">Mayor que</a></li>
							          <li><a data-value="LessThan" href="#">Menor que</a></li>
							          <li><a data-value="Like" href="#">Que contenga</a></li>
							        </ul>
									<input type="hidden" name="typeFilter['.$filter->getName().']">
							      </div><!-- /btn-group -->';
					$html .= $this->formElement(
							$form->get($filter->getName())
								->setAttribute('class', 'form-control'));
					$html .= $this->formElementErrors(
							$form->get($filter->getName()));
					$html .= ' </div><!-- /input-group -->
							  			</div><!-- /.col-lg-6 --> 
									</div><!-- /btn-group -->
							    </div><!-- /input-group -->
							  </div><!-- /.col-lg-6 -->
							</div><!-- /.row -->';
				}
			}
			$html .= '</td>';
		}
	}
	
	return $html;
};

?>

<tr class="filters">
	<td>
		<!--  -->
	</td>
        <?php foreach ($this->grid as $column) : ?>
           <?php echo $treeColumnsPrint($column, $form); ?>
        <?php endforeach; ?>
        <td>
		<div class="btn-group right">
			<button data-toggle="tooltip" data-container="body"
				class="btn btn-info btn-small" type="submit"
				title="<?php echo $this->translate('Aplicar filtros'); ?>">
				<i class="glyphicon glyphicon-search"></i>
			</button>
			<a data-toggle="tooltip" data-container="body"
				class="btn btn-danger btn-small"
				href="<?php echo $this->url(null, array('id' => $this->getHelperPluginManager()->getServiceLocator()->get('controllerpluginmanager')->get('params')->fromRoute('id', 0)) + $filtersClean, true)?>"
				title="<?php echo $this->translate('Limpiar filtros'); ?>"><i
				class="glyphicon glyphicon-remove"></i></a>
		</div>
	</td>
</tr>
<?php echo $this->form()->closeTag(); ?>