<?php

use AtDataGrid\DataGrid\Column\Column;
use Nette\Diagnostics\Debugger;
use Zend\Form\Form;

$form = $this->grid->getFiltersForm();
$form->prepare();
$form->setAttribute('action', $this->url(null, array('action' => 'list')));
$form->setAttribute('method', 'get');
$form->setAttribute('id', 'datagrid-filters-form');

$this instanceof Zend\View\Renderer\PhpRenderer;
$filtersClean = array();
echo $this->form()->openTag($form);

$treeColumnsPrint = function (Column $column, $form) use(&$treeColumnsPrint, $filtersClean) {
	$html = '';
	if ($column->isVisible()) {
		
		$columns = (array) $column->getcolumns();
		$visibleSubcolumns = array();
		foreach ($columns as $_column) {
			if($_column->isVisible()) {
				$visibleSubcolumns[] = $_column;
			}
		
		}
		
		if($columns && count($visibleSubcolumns) > 0) {
			foreach($visibleSubcolumns as $_column) {
				
				$form instanceof Form;
				$fieldset = $form->getFieldsets();
				$html .= $treeColumnsPrint($_column, $fieldset[$column->getName()]);
			}
		} else {
			$html .= '<td>';
			if ($column->hasFilters()) {
				foreach ($column->getFilters() as $filter) {
					$filtersClean[$filter->getName()] = null;
					$html .= $this->formElement($form->get($filter->getName()));
					$html .= $this->formElementErrors($form->get($filter->getName()));
				}
			}
			$html .= '</td>';
		}
		
	}
	
	return $html;
};

?>

    <tr class="filters">
        <td><!--  --></td>
        <?php foreach ($this->grid as $column) : ?>
           <?php echo $treeColumnsPrint($column, $form); ?>
        <?php endforeach; ?>
        <td>
            <div class="btn-group right">
                <button class="btn btn-info btn-small" type="submit" title="<?php echo $this->translate('Apply filters'); ?>"><i class="icon-search icon-white"></i></button>
                <a class="btn btn-danger btn-small" href="<?php echo $this->url(null, array('id' => $this->getHelperPluginManager()->getServiceLocator()->get('controllerpluginmanager')->get('params')->fromRoute('id', 0)) + $filtersClean, true)?>" title="<?php echo $this->translate('Reset filters'); ?>"><i class="icon-remove icon-white"></i></a>
            </div>
        </td>
    </tr>
<?php echo $this->form()->closeTag(); ?>