<?php 

$actionsIcons = array('delete' => '<i class="glyphicon glyphicon-trash"></i>');

?>
<div class="atf-grid-group-actions">
    <div class="btn-group">
    	<button type="button" class="btn btn-danger"><i class="glyphicon glyphicon-wrench"></i> <?php echo $this->translate("Con selección") ?></button>
	  <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown">
	    <span class="caret"></span>
	  </button>
        <ul class="dropdown-menu" role="menu" area-labeledby="drop-bulk">
            <?php foreach($this->gridManager->getActions() as $action) : ?>
                <?php if ($action['bulk'] == true): ?>
                    <li>
                        <a href="#" tabindex="-1" onclick="DataGrid.action('<?php echo $action['action'] ?>')"
                           <?php if (isset($action['confirm-message'])): ?>
                               onclick="return DataGrid.confirmAction(this, '<?php echo $action['confirm-message'] ?>')"
                           <?php endif;?>>
                           <?php echo isset($actionsIcons[$action['action']]) ? $actionsIcons[$action['action']] : '' ?>
                           <?php echo $this->translate($action['label']) ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
</div>