<?php 
use AtDataGrid\DataGrid\Column\Column;
use Nette\Diagnostics\Debugger;
use Zend\Json\Json;

echo $this->viewGridflashMessenger; 

$getColumnCompleteName = function($column, $indice = 0) use(&$getColumnCompleteName){
	if($column->getParent()) {
		$name = $getColumnCompleteName($column->getParent(), $indice++);
	}
	
	$name[] = $column->getName();
	
	return $name;
};

$treeColumnsPrint = function (Column $column) use(&$treeColumnsPrint, $getColumnCompleteName)
{
	$html = '';
	if ($column->isVisible()) {
		$columns = (array) $column->getColumns();
		
		$visibleSubcolumns = array();
		foreach ($columns as $_column) {
			if($_column->isVisible()) {
				$visibleSubcolumns[] = $_column;
			}
				
		}
		
		if($columns && count($visibleSubcolumns) > 0) {
			foreach($visibleSubcolumns as $_column)
				$html .= $treeColumnsPrint($_column);
		} else {
			$html .= '<th '.($column->isHidden() ? 'style="display:none;"' : '').' data-columnid="'.md5(Json::encode($getColumnCompleteName($column))).'">';
			if ($column->isSortable()) {
				$html .= '<a class="sortable" href="' .
				$this->joacubBaseQueryParams(
						array(
							'page' => 1,
							'order' => Json::encode($getColumnCompleteName($column)) . '~' .
							$column->getOrderDirection()
						)) . '">';
				if ($this->grid->getCurrentOrderColumn() == $column) {
					$html .= '<span class="active">';
					$html .=  $column->getLabel();
					if ($this->grid->getCurrentOrderDirection() == 'asc') {
						$html .= ' <i class="glyphicon glyphicon-sort-by-alphabet"></i>';
					} elseif ($this->grid->getCurrentOrderDirection() == 'desc') {
						$html .= ' <i class="glyphicon glyphicon-sort-by-alphabet-alt"></i>';
					}
					$html .= '</span>';
				} else {
					$html .= $column->getLabel();
					$html .= ' <i class="glyphicon glyphicon-sort"></i>';
				}
				$html .= '</a>';
			} else {
				$html .= $column->getLabel();
			}
			$html .= '</th>';
		}
		
	}
	
	return $html;
};

$treeColumnsPrintCanHide = function (Column $column) use(&$treeColumnsPrintCanHide, $getColumnCompleteName)
{
	$html = '';
	if ($column->isVisible()) {
		$columns = (array) $column->getColumns();

		$visibleSubcolumns = array();
		foreach ($columns as $_column) {
			if($_column->isVisible()) {
				$visibleSubcolumns[] = $_column;
			}

		}

		if($columns && count($visibleSubcolumns) > 0) {
			foreach($visibleSubcolumns as $_column)
				$html .= $treeColumnsPrintCanHide($_column);
		} else {
			if ($column->getCanHide()) {
				$idColumn = md5(Json::encode($getColumnCompleteName($column)));
				$html .= '<li data-columnid="'.$idColumn.'">';
				
				$html .= '<span class="can-hide-check todo-actions" style="' . ($column->isHidden() ? 'opacity: 0.25;' : 'opacity: 1;') . ' ">
													<a href="#'.$idColumn.'"><i class="' . ($column->isHidden() ? 'icon-check' : 'icon-check-empty') . '"></i></a>
												</span>
												<span class="desc" style="' . ($column->isHidden() ? 'opacity: 0.25; text-decoration: line-through;' : 'opacity: 1;') . ' ">'.$column->getLabel().'</span> ';
				
				$html .= '</li>';
			} 
			
		}

	}

	return $html;
};

?>
<div class="col-lg-12">
					
					<div class="row">	

						<div class="col-lg-12 col-md-12 col-sm-12">
							<div class="box">
								<div class="box-header">
									<h2><i class="icon-check"></i>Columnas</h2>
									<div class="box-icon">
										<a href="#" class="btn-minimize"><i class="icon-chevron-down"></i></a>
										<a href="#" class="btn-close"><i class="icon-remove"></i></a>
									</div>
								</div>
								<div class="box-content" style="display: none; ">
									<div class="todo">
										<ul class="todo-list ui-sortable">
										 <?php foreach ($this->grid as $column) : ?>
				                            <?php echo $treeColumnsPrintCanHide($column); ?>
				                        <?php endforeach; ?>
										</ul>
									</div>	
								</div>
							</div>
						</div><!--/col-->			
					</div>
					
				</div>
				
					<div class="clearfix"></div>
				
<h2><?php echo $this->translate($this->grid->getCaption()) ?></h2>
<?php if ($this->gridManager->isAllowCreate()): ?>
<a class="btn btn-warning"
	href="<?php echo $this->url(null, array('action' => 'create'), array(), true) ?>"><i
	class="glyphicon glyphicon-plus-sign"></i> <?php echo $this->translate('Crear nuevo') ?> </a>
<?php endif; ?>

        <?php echo $this->viewGridPaginator; ?>
<hr />

<div class="atf-grid">
	<table class="table table-striped">
		<thead>
			<tr>
				<th><input type="checkbox" onclick="DataGrid.checkAll(this)" /></th>
                        <?php foreach ($this->grid as $column) : ?>
                            <?php echo $treeColumnsPrint($column); ?>
                        <?php endforeach; ?>
                        <th class="actions"></th>
			</tr>
		</thead>
		<tbody>

                    <?php echo $this->viewGridFilters ?>
                    <?php if (count($this->data)): ?>
                    
                        <?php echo $this->viewGridRowsList ?>
                    <?php endif ?>

                </tbody>
	</table>
            <?php if (!count($this->data)): ?>
                <div><?php echo $this->translate("No items found.") ?></div>
            <?php endif ?>
        </div>

<?php if (count($this->data)): ?>
            <?php echo $this->viewGridRowsGoupActions ?>
        <?php endif; ?>

<hr />
<?php echo $this->viewGridPaginator; ?>

<script>
$('[data-toggle="tooltip"]').tooltip();

$('.filters .dropdown-menu li').click(function(e) {
	e.preventDefault();
	$(this).closest('ul').find('li').removeClass('active');
	$(this).addClass('active');
	$(this).closest('div').find('input').val($(this).find('a').data('value'));
});
</script>
