<?php $this->headScript()->appendFile($this->basePath() . '/js/at-datagrid/datagrid.js') ?>
<?php $this->headLink()->appendStylesheet($this->basePath() . '/css/at-datagrid/datagrid.css') ?>

<h2><?php echo $this->translate($this->gridManager->getGrid()->getCaption()) ?></h2>
<p>
	<a class="btn btn-default"
		title="<?php echo $this->translate($this->gridManager->getGrid()->getCaptionBackTo()); ?>"
		href="<?php echo $this->backUrl ?>"> <i class="glyphicon glyphicon-arrow-left"></i>
        <?php echo $this->translate($this->gridManager->getGrid()->getCaptionBackTo()); ?>
        </a>
</p>
<?php
echo $this->render($this->formTemplate)?>
