<?php 

use Zend\Form\Element\Select;
use Nette\Diagnostics\Debugger;
use Zend\Json\Json;
$element = $column->getFormElement();

if($element instanceof Select) {
	$values = $element->getValueOptions();
	if(is_string($value)) {
	    if(isset($values[$value]))
		  $value = $values[$value];
	} else {
	    $value = is_array($value) ? 'Valor no soportado' : $value;
	}
}
?>
<td <?php echo $column->isHidden() ? 'style="display:none;"' : '' ?> class="<?php echo 'col-' . $column->getName() ?>"><?php echo $value ?></td>