<?php 

use Nette\Diagnostics\Debugger;
$hydrator = new DoctrineModule\Stdlib\Hydrator\DoctrineObject($this->gridManager->getGrid()->getDatasource()->getEm(), $this->gridManager->getGrid()->getDatasource()->getEntity());

$actionsIcons = array('delete' => '<i class="icon-trash"></i>');
?>
<form method="post" action="" id="datagrid-list-form">
    <?php foreach ($this->data as $row) : 
    $columnIdentifier = ucfirst($this->gridManager->getGrid()->getIdentifierColumnName());
    ?>
        <tr>
            <td>
                <input class="grid-table-checker" type="checkbox" value="<?php echo $row->{"get" . $columnIdentifier}() ?>" id="item_id_<?php echo $row->{"get" . $columnIdentifier}() ?>" name="items[]"/>
            </td>

            <?php foreach ($this->columns as $collumn) : ?>
            
                <?php if (isset($collumn) && $collumn->isVisible()): ?>
                
                <?php 
                
                $value = $row->{"get" . ucfirst($collumn->getName())}();
				$arrayOrViewModel = $collumn->render($value, $row);
				
				if(!$arrayOrViewModel instanceof Zend\View\Model\ViewModel){
					Debugger::dump($collumn);
exit;
				}
				
				if(is_array($arrayOrViewModel)) {
					foreach($arrayOrViewModel as $viewModel)
						echo $this->render($viewModel);
				} else {
					echo $this->render($arrayOrViewModel);
				}
                
                
                ?>
                <?php endif; ?>
            <?php endforeach; ?>

            <td>
                <div class="btn-group pull-right">
                    <?php foreach($this->gridManager->getButtonActions() as $action) : ?>
                        <a class="btn btn-small" href="<?php echo $this->url(null, array('action' => $action['action'], 'id' => $row->{"get" . $columnIdentifier}() )) ?>"
                            <?php if (isset($action['confirm-message'])): ?>
                            onclick="return DataGrid.confirmAction(this, '<?php echo $action['confirm-message'] ?>')"
                            <?php endif;?>>
                            <i title="<?php echo $this->translate($action['label']) ?>" class="<?php echo $action['class'] ?>"></i>
                        </a>
                    <?php endforeach; ?>
                    <a class="btn btn-small dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <?php foreach($this->gridManager->getActions() as $action) : ?>
                            <?php if ($action['button'] == false): ?>
                            <li>
                                <a href="<?php echo $this->url(null, array('action' => $action['action'], 'id' => $row->{"get" . $columnIdentifier}())) ?>"
                                    <?php if (isset($action['confirm-message'])): ?>
                                        onclick="return DataGrid.confirmAction(this, '<?php echo $action['confirm-message'] ?>')"
                                    <?php endif;?>>
                                    <?php echo isset($actionsIcons[$action['action']]) ? $actionsIcons[$action['action']] : '' ?>
                                    <?php echo $this->translate($action['label']) ?>
                                </a>
                            </li>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </td>
        </tr>
    <?php endforeach; ?>
    <input type="hidden" value="" id="datagrid-list-form-action" name="cmd"/>
</form>